// Every word on the site, both languages. The build renders one page per
// language, so keep the two structures identical and change only the words.
// House rules: first person, plain sentences, specifics over adjectives,
// no long dashes.

export const site = {
  domain: 'cambora.cz',
  repo: 'https://github.com/jozso39/cambora.cz',
  github: 'https://github.com/jozso39',
  linkedin: 'https://www.linkedin.com/in/jozef-cambora',
  // Assembled in the browser after the háček puzzle; never in the HTML.
  email: { u: 'jozef', d: 'cambora', t: 'cz' },
  photo: 'jozef.jpg',
  og: 'og.jpg',
  themeLight: '#f4f2ed',
  themeDark: '#151513',
}

const links = {
  huginn: 'https://github.com/jozso39/huginn',
  jev: 'https://github.com/jozso39/jev-model-router-for-claude',
  realiterier: 'https://realiterier.cambora.cz/',
  deskohrani: 'https://deskohrani.cambora.cz/',
  zizkostel: 'https://zizkostel.cambora.cz/cs',
}

export const content = {
  en: {
    lang: 'en',
    path: '/',
    other: 'cs',
    otherHref: './cs/',
    otherLabel: 'česky',
    title: 'Jozef Čambora, AI engineer in Prague',
    description:
      'QA and release engineering first, now building and measuring AI features at Medevio. What I run, where I worked, how to reach me.',
    skip: 'Skip to content',
    navLabel: 'Sections',
    nav: { now: 'now', work: 'things I run', before: 'before', contact: 'write me' },
    hero: {
      name: 'Jozef Čambora',
      role: 'AI engineer · Prague · at Medevio since 2026',
      photoAlt: 'Jozef Čambora',
      intro: [
        'I came from QA through release engineering to <em>full-stack development</em> and <em>building AI product features</em>. At Medevio, a platform Czech and Slovak clinics use to talk to their patients, I build AI features that help doctors and nurses save time on administrative work so they can focus more on their patients.',
        'Most of the code I ship these days is written by coding agents. My job is to set the rules they work under, read what comes out, and measure it.',
        'Most of the projects below run on my Raspberry Pi, and so do some of my agents. I can work from wherever my phone is: I send an agent a task, it works on the Pi, and I check the result later.',
      ],
      links: { github: 'GitHub', linkedin: 'LinkedIn', email: 'e-mail is at the bottom' },
    },
    now: {
      k: 'now',
      sub: 'since 2026',
      title: 'Medevio',
      paras: [
        'I own the AI parts of the product: drafted replies for doctors, summaries of patient requests in Czech and Slovak, processing of calls and text messages, transcripts of meetings. Prompt, code, rollout, and the evaluation that decides whether it ships at all.',
        'We work agent-first. I keep the conventions, skills and runbooks the agents follow, with credentials cut so an agent can run a data job but can’t touch a live clinic. The part I care about most is evaluation: judges with repeated votes, holdout sets, significance tests. Changes that don’t survive the numbers get dropped, including a few of mine.',
      ],
      stack: 'typescript · bun · fastify · postgres · aws · terraform · gitlab ci · langfuse · claude code · mcp',
    },
    work: {
      k: 'things I run',
      lead: 'Real, running, and mine. Much of it lives on a Raspberry Pi in my flat. The line under each one says what the build script found when it checked the link.',
      projects: [
        {
          title: 'Huginn',
          when: 'since sep 2026',
          status: 'in daily use',
          text: 'One inbox for Slack, Gmail, ClickUp, GitLab and Signal. I was tired of five apps asking for attention, so I wrote one dashboard where I can reply, draft, react or mark things done, and it learns from what I mark as spam or important. It started on the Pi and is now a Mac app, with tokens encrypted at rest.',
          stack: 'bun · hono · sqlite · react · tauri',
          link: { href: links.huginn, label: 'source on GitHub' },
        },
        {
          title: 'Jev model router for Claude Code',
          when: 'since sep 2026',
          status: 'in daily use',
          text: 'A small proxy that picks the model for each Claude Code turn: cheap ones for cheap turns, the expensive one when it matters, every decision logged. It exists because I looked at my bill.',
          stack: 'typescript · openrouter',
          link: { href: links.jev, label: 'source on GitHub' },
        },
        {
          title: 'Realiterier',
          when: 'web since oct 2026',
          status: 'scraper paused',
          text: 'A watchdog for Czech property listings. It pulls ads from four portals, reads the text with an LLM for things the portals don’t filter on (pets allowed, no commission, brick or panel), groups the same flat across portals, flags the usual scam patterns and mails you within minutes. Right now only the web part runs; the scraper stays off until I decide what to do with it.',
          stack: 'bun · postgres · drizzle · ses · stripe',
          link: { href: links.realiterier, label: 'the site, in Czech' },
        },
        {
          title: 'kviff.ai',
          when: 'asleep until july',
          status: 'seasonal',
          text: 'A chat guide to the Karlovy Vary film festival. It crawls the programme, pulls film data from TMDB, OMDB and ČSFD, and answers questions like what fits between two screenings. It wakes up for the festival in July and sleeps the rest of the year, which is also when I stop paying for it.',
          stack: 'bun · mastra · postgres · next.js · crawlee',
        },
        {
          title: 'Deskohraní',
          when: 'since sep 2026',
          status: 'live',
          text: 'Sign-ups for the board-game club I run on Thursdays: a form behind a home-made dice captcha, a capacity that closes the form on its own, attendance, articles, CSV export, nightly backups. Node 22 with nothing but the standard library, in Docker behind a Cloudflare tunnel.',
          stack: 'node 22 · node:sqlite · docker',
          link: { href: links.deskohrani, label: 'the site, in Czech' },
        },
        {
          title: 'Žižkostel',
          when: 'demo',
          status: 'not launched yet',
          text: 'A new website for a community centre in Prague 3, built so its editors can publish events without calling a developer: Payload CMS with a Czech admin, drafts and versions, two languages with Czech as the fallback. The client is still writing the content; the demo runs on my domain.',
          stack: 'payload cms · next.js · sqlite',
          link: { href: links.zizkostel, label: 'the demo, in Czech' },
        },
        {
          title: 'The Pi itself',
          when: 'since sep 2026',
          status: 'running',
          text: 'A Raspberry Pi 5 in my flat hosts the sites above, plus a Signal assistant with local Czech speech-to-text, a private family app, and nightly encrypted backups to S3. A watchdog speaks up only when a backup goes stale, which is the one kind of monitoring I trust.',
          stack: 'raspberry pi · docker · systemd · cloudflare tunnel · restic',
        },
      ],
      more: 'Smaller things on GitHub: MCP servers, LangGraph examples, scrapers.',
    },
    before: {
      k: 'before',
      items: [
        {
          when: '2025 to 2026',
          where: 'ABUGO Group',
          role: 'AI automation engineer',
          text: 'Internal agents in n8n, Make and TypeScript: an AI-policy agent, website classification, a recruiting bot for Slack.',
        },
        {
          when: '2020 to 2025',
          where: 'Make (Celonis)',
          role: 'Developer experience engineer, before that QA lead',
          text: 'Release management, automated instance deployments, and the push that got the company testing earlier instead of later.',
        },
        {
          when: '2016 to 2020',
          where: 'Rohlík, Zonky, Accenture',
          role: 'QA engineer, test analyst',
          text: 'An online grocer, a fintech, enterprise clients.',
        },
      ],
      certs: 'robot_dreams AI developer, 2025 · Harvard CS50, 2020',
    },
    contact: {
      k: 'write me',
      text: 'For work, a project, or because something above is wrong. The address is behind one small chore so scrapers don’t get it: put the háček where it belongs.',
      hint: 'Drag the ˇ onto the C, or just tap the C.',
      targetLabel: 'Put the háček on the C and show the e-mail address',
      success: 'That’s the one.',
      copy: 'copy',
      copied: 'copied',
      noscript: 'No JavaScript? jozef at cambora dot cz.',
      elsewhere: 'Also on',
    },
    verify: { checked: 'checked', noAnswer: 'no answer', noLink: 'no public link' },
    footer: {
      made: 'Plain HTML and CSS, no framework, on GitHub Pages so it stays up when the Pi doesn’t.',
      built: 'Built {date} at {time}. The project links above were fetched during the build and answered as noted.',
      domain: 'The domain has no háček because .cz doesn’t allow one.',
      source: 'source',
      who: 'Jozef Čambora · Prague',
    },
  },

  cs: {
    lang: 'cs',
    path: '/cs/',
    other: 'en',
    otherHref: '../',
    otherLabel: 'english',
    title: 'Jozef Čambora, AI inženýr z Prahy',
    description:
      'Nejdřív QA a release engineering, teď stavím a měřím AI funkce v Medeviu. Co mi běží, kde jsem pracoval, jak mě sehnat.',
    skip: 'Přeskočit na obsah',
    navLabel: 'Části stránky',
    nav: { now: 'teď', work: 'co mi běží', before: 'předtím', contact: 'napište mi' },
    hero: {
      name: 'Jozef Čambora',
      role: 'AI inženýr · Praha · v Medeviu od roku 2026',
      photoAlt: 'Jozef Čambora',
      intro: [
        'Od QA jsem se přes release engineering dostal k <em>full-stack vývoji</em> a <em>budování AI automatizací a AI funkcí do produktu</em>. V Medeviu, přes které si české a slovenské ordinace píšou s pacienty, stavím AI funkce, které lékařům a sestrám šetří čas s administrativou, aby se mohli víc věnovat pacientům.',
        'Většinu kódu, který merguju a deployuju, píšou coding agenti, které si stavím sám. Moje práce je hlavně správně formulovat požadavky a kontrolovat jejich výstup.',
        'Většina projektů níž běží na mém Raspberry Pi a běží tam i část mých agentů. Pracovat můžu odkudkoli, kde mám telefon: pošlu agentovi úkol, ten na něm pracuje na Pi a já si výsledek zkontroluju později.',
      ],
      links: { github: 'GitHub', linkedin: 'LinkedIn', email: 'e-mail je dole' },
    },
    now: {
      k: 'teď',
      sub: 'od roku 2026',
      title: 'Medevio',
      paras: [
        'Mám na starosti AI části produktu: návrhy odpovědí pro lékaře, shrnutí požadavků pacientů česky i slovensky, zpracování hovorů a SMS, přepisy schůzek. Prompt, kód, nasazení a vyhodnocení, které rozhodne, jestli to vůbec půjde ven.',
        'Pracujeme agent-first. Udržuju konvence, skilly a runbooky, podle kterých agenti jedou, s přístupy ořezanými tak, aby agent mohl spustit datovou úlohu, ale nesáhl na ostrou ordinaci. Nejvíc mi záleží na vyhodnocení: soudci s opakovaným hlasováním, holdout sady, testy významnosti. Co neprojde čísly, letí, včetně pár mých vlastních nápadů.',
      ],
      stack: 'typescript · bun · fastify · postgres · aws · terraform · gitlab ci · langfuse · claude code · mcp',
    },
    work: {
      k: 'co mi běží',
      lead: 'Skutečné, běžící a moje. Hodně z toho bydlí na Raspberry Pi u mě v bytě. Řádek pod každou položkou říká, co build skript zjistil, když odkaz zkontroloval.',
      projects: [
        {
          title: 'Huginn',
          when: 'od září 2026',
          status: 'používám denně',
          text: 'Jedna schránka pro Slack, Gmail, ClickUp, GitLab a Signal. Unavilo mě pět aplikací, které se hlásí o pozornost, tak jsem napsal jeden dashboard, kde odpovím, rozepíšu, zareaguju nebo odškrtnu, a který se učí z toho, co označím jako spam nebo důležité. Začal na Pi, dnes je to aplikace pro Mac, tokeny šifrované na disku.',
          stack: 'bun · hono · sqlite · react · tauri',
          link: { href: links.huginn, label: 'zdroják na GitHubu' },
        },
        {
          title: 'Jev model router pro Claude Code',
          when: 'od září 2026',
          status: 'používám denně',
          text: 'Malá proxy, která pro každý tah Claude Code vybere model: levný na levné tahy, drahý, když na tom záleží, každé rozhodnutí zalogované. Vznikla, když jsem se podíval na účet.',
          stack: 'typescript · openrouter',
          link: { href: links.jev, label: 'zdroják na GitHubu' },
        },
        {
          title: 'Realiterier',
          when: 'web od října 2026',
          status: 'scraper stojí',
          text: 'Hlídač inzerátů na české reality. Stahuje inzeráty ze čtyř portálů, čte text přes LLM kvůli věcem, podle kterých portály filtrovat neumí (zvířata povolena, bez provize, cihla nebo panel), slučuje stejný byt napříč portály, označí obvyklé podvodné vzorce a do pár minut pošle e-mail. Teď běží jen webová část; scraper zůstává vypnutý, dokud se nerozhodnu, co s ním.',
          stack: 'bun · postgres · drizzle · ses · stripe',
          link: { href: links.realiterier, label: 'web' },
        },
        {
          title: 'kviff.ai',
          when: 'spí do července',
          status: 'sezónní',
          text: 'Chatový průvodce festivalem v Karlových Varech. Projde program, stáhne data o filmech z TMDB, OMDB a ČSFD a odpoví třeba na to, co se vejde mezi dvě projekce. Probouzí se na festival v červenci a zbytek roku spí, což je i doba, kdy za něj neplatím.',
          stack: 'bun · mastra · postgres · next.js · crawlee',
        },
        {
          title: 'Deskohraní',
          when: 'od září 2026',
          status: 'běží',
          text: 'Přihlášky do kroužku deskových her, který vedu ve čtvrtek: formulář za vlastní kostkovou captchou, kapacita, která formulář sama zavře, docházka, články, export do CSV, noční zálohy. Node 22 jen se standardní knihovnou, v Dockeru za Cloudflare tunelem.',
          stack: 'node 22 · node:sqlite · docker',
          link: { href: links.deskohrani, label: 'web' },
        },
        {
          title: 'Žižkostel',
          when: 'demo',
          status: 'ještě nespuštěno',
          text: 'Nový web komunitního centra na Praze 3, postavený tak, aby redakce zveřejňovala akce bez volání vývojáři: Payload CMS s českou administrací, koncepty a verze, dva jazyky s češtinou jako záchranou. Klient ještě píše obsah; demo běží na mé doméně.',
          stack: 'payload cms · next.js · sqlite',
          link: { href: links.zizkostel, label: 'demo' },
        },
        {
          title: 'Samotné Pi',
          when: 'od září 2026',
          status: 'běží',
          text: 'Raspberry Pi 5 u mě v bytě hostuje weby výš, k tomu asistenta na Signalu s lokálním českým přepisem řeči, soukromou rodinnou aplikaci a noční šifrované zálohy do S3. Hlídač se ozve, jen když záloha zestárne, což je jediný druh monitoringu, kterému věřím.',
          stack: 'raspberry pi · docker · systemd · cloudflare tunnel · restic',
        },
      ],
      more: 'Menší věci na GitHubu: MCP servery, příklady s LangGraphem, scrapery.',
    },
    before: {
      k: 'předtím',
      items: [
        {
          when: '2025 až 2026',
          where: 'ABUGO Group',
          role: 'AI automation engineer',
          text: 'Interní agenti v n8n, Make a TypeScriptu: agent pro firemní AI politiku, klasifikace webů, náborový bot pro Slack.',
        },
        {
          when: '2020 až 2025',
          where: 'Make (Celonis)',
          role: 'Developer experience engineer, předtím QA lead',
          text: 'Release management, automatizované nasazování instancí a tlak na to, aby se ve firmě testovalo dřív, ne později.',
        },
        {
          when: '2016 až 2020',
          where: 'Rohlík, Zonky, Accenture',
          role: 'QA engineer, test analyst',
          text: 'Online supermarket, fintech, enterprise klienti.',
        },
      ],
      certs: 'robot_dreams AI developer, 2025 · Harvard CS50, 2020',
    },
    contact: {
      k: 'napište mi',
      text: 'Kvůli práci, projektu, nebo protože je něco výš špatně. Adresa je za jednou malou prací, aby ji nesbírali roboti: dejte háček tam, kam patří.',
      hint: 'Přetáhněte ˇ na C, nebo na C prostě klepněte.',
      targetLabel: 'Dát háček na C a zobrazit e-mailovou adresu',
      success: 'Přesně tak.',
      copy: 'kopírovat',
      copied: 'zkopírováno',
      noscript: 'Bez JavaScriptu: jozef zavináč cambora tečka cz.',
      elsewhere: 'Taky na',
    },
    verify: { checked: 'ověřeno', noAnswer: 'bez odpovědi', noLink: 'bez veřejného odkazu' },
    footer: {
      made: 'Čisté HTML a CSS, žádný framework, na GitHub Pages, aby to běželo, i když Pi zrovna ne.',
      built: 'Sestaveno {date} v {time}. Odkazy na projekty výš byly při sestavení staženy a odpověděly tak, jak je uvedeno.',
      domain: 'Doména háček nemá, .cz ho nedovolí.',
      source: 'zdroják',
      who: 'Jozef Čambora · Praha',
    },
  },
}
