// All text on the site, both languages. The build renders one page per language.
// Keep both in sync: the structure must match, only the words differ.

export const site = {
  domain: 'cambora.cz',
  repo: 'https://github.com/jozso39/cambora.cz',
  github: 'https://github.com/jozso39',
  linkedin: 'https://www.linkedin.com/in/jozef-cambora',
  // The address is assembled in the browser after the háček puzzle, so it
  // never appears in the HTML as something a scraper can match.
  email: { u: 'jozef', d: 'cambora', t: 'cz' },
  photo: 'jozef.jpg',
  og: 'og.jpg',
  accentLight: '#faf7f2',
  accentDark: '#141518',
}

const links = {
  huginn: 'https://github.com/jozso39/huginn',
  jev: 'https://github.com/jozso39/jev-model-router-for-claude',
  deskohrani: 'https://deskohrani.cambora.cz/',
  zizkostel: 'https://zizkostel.cambora.cz/cs',
  realiterier: 'https://realiterier.cambora.cz/',
}

export const content = {
  en: {
    lang: 'en',
    path: '/',
    other: 'cs',
    otherHref: './cs/',
    otherLabel: 'Česky',
    title: 'Jozef Čambora — AI Engineer, Prague',
    description:
      'AI engineer in Prague. I ship production AI features agent-first and build the harness that makes them reliable. Projects, background, contact.',
    skip: 'Skip to content',
    nav: { work: 'Work', now: 'Now', before: 'Before', contact: 'Contact' },
    hero: {
      name: 'Jozef Čambora',
      role: 'AI Engineer · Prague',
      photoAlt: 'Jozef Čambora',
      intro: [
        'I build production software agent-first — coding agents write most of the code, I own the architecture, the review and what ships — and I build the harness that makes that reliable: conventions, skills, runbooks and evaluation loops.',
        'At Medevio I ship AI features into a healthcare product used by clinics in Czechia and Slovakia. Ten years in QA and release engineering before that is why I measure what agents produce instead of trusting it.',
      ],
      links: { github: 'GitHub', linkedin: 'LinkedIn', email: 'E-mail' },
    },
    now: {
      label: 'Now',
      title: 'AI Engineer at Medevio',
      since: 'since 2026',
      lead: 'Medevio is a patient–doctor communication platform. I own the AI inside it, from prompt to rollout.',
      bullets: [
        'AI features in production: drafted replies for doctors, request summaries in Czech and Slovak, call and SMS processing, meeting transcription.',
        'Agent-first delivery across the team’s repositories: conventions, skills and executable runbooks that coding agents work against — with scoped credentials, so an agent can run a data job but never touch a live clinic.',
        'Evaluation as the deciding step: LLM judges, holdout sets and significance tests. A change ships when the measurement says it helped, and gets killed when it doesn’t.',
        'Production TypeScript — Bun, Fastify, PostgreSQL — on AWS with Terraform and GitLab CI.',
      ],
      stack: ['TypeScript', 'Bun', 'PostgreSQL', 'AWS', 'Langfuse', 'Claude Code', 'MCP'],
    },
    work: {
      label: 'Selected work',
      title: 'Things I built and run',
      intro: 'Everything here is real and mine. Most of it runs on a Raspberry Pi at home.',
      projects: [
        {
          title: 'Huginn',
          state: 'on',
          status: 'in daily use',
          tagline: 'One inbox for every channel I have to answer.',
          desc: 'Slack, Gmail, ClickUp, GitLab and Signal in one self-hosted dashboard: reply, draft, react or mark done from one place, with triage rules that learn from what I mark important or spam. OAuth through a static relay page, tokens sealed at rest, Web Push to the phone.',
          stack: ['Bun', 'Hono', 'SQLite', 'React', 'OAuth'],
          link: { href: links.huginn, label: 'Source on GitHub' },
        },
        {
          title: 'Jev model router for Claude Code',
          state: 'on',
          status: 'in daily use',
          tagline: 'Cheap turns on cheap models, the big model when it matters.',
          desc: 'Per-turn model routing for Claude Code through one OpenRouter key: a local proxy classifies each request, picks the model and logs every decision. Zero-retention routing by design.',
          stack: ['TypeScript', 'OpenRouter', 'Claude Code'],
          link: { href: links.jev, label: 'Source on GitHub' },
        },
        {
          title: 'Realiterier',
          state: 'wip',
          status: 'live, scraper paused',
          tagline: 'A real-estate watchdog that reads the ad text.',
          desc: 'Scrapes four Czech property portals, normalises ads into PostgreSQL and extracts with an LLM what portals don’t categorise — pets allowed, no commission, brick or panel. Groups the same flat across portals, flags scam patterns and e-mails matching ads within minutes. Prepaid watchdogs through Stripe.',
          stack: ['Bun', 'PostgreSQL', 'Drizzle', 'SES', 'Stripe', 'hexagonal'],
          note: 'The web app runs on the Pi; the scraper and paid APIs are switched off, so no new ads flow in for now.',
          link: { href: links.realiterier, label: 'Live site (Czech)' },
        },
        {
          title: 'kviff.ai',
          state: 'off',
          status: 'seasonal',
          tagline: 'An AI guide to the Karlovy Vary film festival.',
          desc: 'Crawls the festival programme, enriches films from TMDB, OMDB and ČSFD, embeds them and answers in chat: what to see tonight, what fits between two screenings, how far the venues are from each other. Per-user and global token budgets keep the bill predictable.',
          stack: ['Bun', 'Mastra', 'PostgreSQL', 'Next.js', 'Crawlee', 'Langfuse'],
          note: 'Runs during the festival in July; hibernated between editions.',
        },
        {
          title: 'Deskohraní',
          state: 'on',
          status: 'live',
          tagline: 'Registrations for the kids’ board-game club I run.',
          desc: 'Sign-up form behind a self-made dice captcha, a capacity that closes the form itself, attendance per lesson, articles, CSV export, nightly backups. Zero-dependency Node 22 with node:sqlite, in Docker behind a Cloudflare tunnel.',
          stack: ['Node 22', 'node:sqlite', 'Docker', 'Cloudflare'],
          link: { href: links.deskohrani, label: 'Live site (Czech)' },
        },
        {
          title: 'Žižkostel',
          state: 'wip',
          status: 'in progress',
          tagline: 'A community centre’s website its editors can run themselves.',
          desc: 'Payload CMS and Next.js for a Prague community and cultural centre: events that fall into the archive by date, a Czech admin, drafts and versions, bilingual with Czech fallback, and roles an editor cannot escalate.',
          stack: ['Payload CMS', 'Next.js', 'SQLite', 'Docker'],
          link: { href: links.zizkostel, label: 'Demo (Czech)' },
        },
        {
          title: 'The home server',
          state: 'on',
          status: 'running',
          tagline: 'A Raspberry Pi that holds everything together.',
          desc: 'A Signal assistant with local Czech speech-to-text, Gmail and Calendar tooling, a private family app and this site’s siblings — all in Docker behind one Cloudflare tunnel, with nightly restic backups to S3 and a watchdog that only speaks when a backup goes stale. AWS access bounded by IAM permission boundaries, every call audited.',
          stack: ['Raspberry Pi', 'Docker', 'systemd', 'Cloudflare', 'restic', 'AWS IAM'],
        },
      ],
      more: 'More on GitHub: MCP servers, LangGraph examples, scrapers.',
      moreLabel: 'github.com/jozso39',
    },
    before: {
      label: 'Before',
      title: 'Ten years of making software testable',
      items: [
        {
          when: '2025 – 2026',
          where: 'ABUGO Group',
          role: 'AI Automation Engineer',
          text: 'AI agents for internal operations in n8n, Make and TypeScript: an AI-policy agent, website classification, a recruitment bot for Slack.',
        },
        {
          when: '2020 – 2025',
          where: 'Make (Celonis)',
          role: 'Developer Experience Engineer, before that QA Lead',
          text: 'Release management and automated instance deployment. Started and drove the company-wide shift-left on quality.',
        },
        {
          when: '2016 – 2020',
          where: 'Rohlík.cz · Zonky.cz · Accenture',
          role: 'QA Engineer, Test Engineering Analyst',
          text: 'Test automation for an online grocer, a fintech and enterprise clients.',
        },
      ],
      certs: 'AI Developer (robot_dreams, 2025) · CS50 (Harvard / edX, 2020)',
    },
    contact: {
      label: 'Contact',
      title: 'Say hello',
      text: 'Hiring, a project, or a question about any of this — write to me. The address is behind a small proof that you are not a robot harvesting e-mails:',
      hint: 'Give my name its háček — drag the ˇ onto the C, or just tap the C.',
      targetLabel: 'Add the háček to the C and reveal the e-mail address',
      success: 'Thank you. That is how it is written.',
      copy: 'Copy',
      copied: 'Copied',
      noscript: 'Without JavaScript: jozef at cambora dot cz.',
      elsewhere: 'Or find me on',
    },
    footer: {
      made: 'Plain HTML and CSS, no framework, hosted on GitHub Pages.',
      source: 'Source',
      who: 'Jozef Čambora · Prague · 2026',
    },
  },

  cs: {
    lang: 'cs',
    path: '/cs/',
    other: 'en',
    otherHref: '../',
    otherLabel: 'English',
    title: 'Jozef Čambora — AI inženýr, Praha',
    description:
      'AI inženýr z Prahy. Dodávám produkční AI funkce agent-first a stavím infrastrukturu, díky které se na ně dá spolehnout. Projekty, zkušenosti, kontakt.',
    skip: 'Přeskočit na obsah',
    nav: { work: 'Práce', now: 'Teď', before: 'Předtím', contact: 'Kontakt' },
    hero: {
      name: 'Jozef Čambora',
      role: 'AI inženýr · Praha',
      photoAlt: 'Jozef Čambora',
      intro: [
        'Stavím produkční software agent-first — většinu kódu píšou kódovací agenti, já vlastním architekturu, review a to, co jde ven — a stavím k tomu zázemí, díky kterému se na to dá spolehnout: konvence, skilly, runbooky a vyhodnocovací smyčky.',
        'V Medeviu dodávám AI funkce do zdravotnického produktu, který používají ordinace v Česku a na Slovensku. Deset let v QA a release engineeringu před tím je důvod, proč to, co agenti vyrobí, měřím, místo abych tomu věřil.',
      ],
      links: { github: 'GitHub', linkedin: 'LinkedIn', email: 'E-mail' },
    },
    now: {
      label: 'Teď',
      title: 'AI inženýr v Medeviu',
      since: 'od roku 2026',
      lead: 'Medevio je platforma pro komunikaci mezi pacientem a lékařem. Mám na starosti AI, která v ní běží — od promptu po nasazení.',
      bullets: [
        'AI funkce v produkci: návrhy odpovědí pro lékaře, shrnutí požadavků česky i slovensky, zpracování hovorů a SMS, přepis schůzek.',
        'Agent-first vývoj napříč repozitáři týmu: konvence, skilly a spustitelné runbooky, proti kterým kódovací agenti pracují — s omezenými přístupy, takže agent může spustit datovou úlohu, ale nikdy nesáhne na ostrou ordinaci.',
        'Vyhodnocení jako rozhodující krok: LLM soudci, holdout sady, testy významnosti. Změna jde ven, když měření ukáže, že pomohla — a končí, když ne.',
        'Produkční TypeScript — Bun, Fastify, PostgreSQL — na AWS s Terraformem a GitLab CI.',
      ],
      stack: ['TypeScript', 'Bun', 'PostgreSQL', 'AWS', 'Langfuse', 'Claude Code', 'MCP'],
    },
    work: {
      label: 'Vybraná práce',
      title: 'Co jsem postavil a provozuju',
      intro: 'Všechno tady je skutečné a moje. Většina z toho běží na Raspberry Pi u mě doma.',
      projects: [
        {
          title: 'Huginn',
          state: 'on',
          status: 'používám denně',
          tagline: 'Jedna schránka pro všechny kanály, na které musím odpovídat.',
          desc: 'Slack, Gmail, ClickUp, GitLab a Signal v jednom self-hostovaném dashboardu: odpovědět, rozepsat, reagovat nebo odškrtnout z jednoho místa, s třídicími pravidly, která se učí z toho, co označím jako důležité nebo spam. OAuth přes statickou relay stránku, tokeny šifrované na disku, Web Push na telefon.',
          stack: ['Bun', 'Hono', 'SQLite', 'React', 'OAuth'],
          link: { href: links.huginn, label: 'Zdrojový kód na GitHubu' },
        },
        {
          title: 'Jev model router pro Claude Code',
          state: 'on',
          status: 'používám denně',
          tagline: 'Levné tahy na levných modelech, velký model, když na tom záleží.',
          desc: 'Směrování modelů pro Claude Code po jednotlivých tazích přes jeden klíč k OpenRouteru: lokální proxy každý požadavek zařadí, vybere model a každé rozhodnutí zaloguje. Routing bez uchovávání dat, záměrně.',
          stack: ['TypeScript', 'OpenRouter', 'Claude Code'],
          link: { href: links.jev, label: 'Zdrojový kód na GitHubu' },
        },
        {
          title: 'Realiterier',
          state: 'wip',
          status: 'běží, scraper stojí',
          tagline: 'Hlídací pes na reality, který čte text inzerátu.',
          desc: 'Stahuje inzeráty ze čtyř českých realitních portálů, normalizuje je do PostgreSQL a pomocí LLM vytahuje to, co portály nekategorizují — zvířata povolena, bez provize, cihla nebo panel. Slučuje stejný byt napříč portály, označuje podvodné vzorce a do pár minut posílá e-mailem odpovídající inzeráty. Předplacení hlídači přes Stripe.',
          stack: ['Bun', 'PostgreSQL', 'Drizzle', 'SES', 'Stripe', 'hexagonální architektura'],
          note: 'Web běží na Pi; scraper a placená API jsou vypnuté, nové inzeráty zatím nepřitékají.',
          link: { href: links.realiterier, label: 'Živý web' },
        },
        {
          title: 'kviff.ai',
          state: 'off',
          status: 'sezónní',
          tagline: 'AI průvodce festivalem v Karlových Varech.',
          desc: 'Prochází program festivalu, obohacuje filmy z TMDB, OMDB a ČSFD, vytváří embeddingy a odpovídá v chatu: co vidět dnes večer, co se vejde mezi dvě projekce, jak daleko jsou sály od sebe. Rozpočty tokenů na uživatele i celkem drží účet předvídatelný.',
          stack: ['Bun', 'Mastra', 'PostgreSQL', 'Next.js', 'Crawlee', 'Langfuse'],
          note: 'Běží během festivalu v červenci, mezi ročníky spí.',
        },
        {
          title: 'Deskohraní',
          state: 'on',
          status: 'běží',
          tagline: 'Přihlášky do dětského kroužku deskových her, který vedu.',
          desc: 'Přihlašovací formulář za vlastní kostkovou captchou, kapacita, která formulář sama zavře, docházka po lekcích, články, export do CSV, noční zálohy. Node 22 bez závislostí s node:sqlite, v Dockeru za Cloudflare tunelem.',
          stack: ['Node 22', 'node:sqlite', 'Docker', 'Cloudflare'],
          link: { href: links.deskohrani, label: 'Živý web' },
        },
        {
          title: 'Žižkostel',
          state: 'wip',
          status: 'rozpracováno',
          tagline: 'Web komunitního centra, který si redakce spravuje sama.',
          desc: 'Payload CMS a Next.js pro pražské komunitní a kulturní centrum: akce, které podle data samy padají do archivu, česká administrace, koncepty a verze, dvojjazyčnost s českým fallbackem a role, které si editor nemůže povýšit.',
          stack: ['Payload CMS', 'Next.js', 'SQLite', 'Docker'],
          link: { href: links.zizkostel, label: 'Demo' },
        },
        {
          title: 'Domácí server',
          state: 'on',
          status: 'běží',
          tagline: 'Raspberry Pi, které drží všechno pohromadě.',
          desc: 'Asistent na Signalu s lokálním českým přepisem řeči, nástroje pro Gmail a Kalendář, soukromá rodinná aplikace a sourozenci tohoto webu — všechno v Dockeru za jedním Cloudflare tunelem, s nočními zálohami přes restic do S3 a hlídačem, který se ozve, jen když záloha zestárne. Přístup do AWS ohraničený IAM permission boundaries, každé volání auditované.',
          stack: ['Raspberry Pi', 'Docker', 'systemd', 'Cloudflare', 'restic', 'AWS IAM'],
        },
      ],
      more: 'Další na GitHubu: MCP servery, příklady s LangGraphem, scrapery.',
      moreLabel: 'github.com/jozso39',
    },
    before: {
      label: 'Předtím',
      title: 'Deset let, kdy jsem dělal software testovatelným',
      items: [
        {
          when: '2025 – 2026',
          where: 'ABUGO Group',
          role: 'AI Automation Engineer',
          text: 'AI agenti pro interní provoz v n8n, Make a TypeScriptu: agent pro firemní AI politiku, klasifikace webů, náborový bot pro Slack.',
        },
        {
          when: '2020 – 2025',
          where: 'Make (Celonis)',
          role: 'Developer Experience Engineer, předtím QA Lead',
          text: 'Release management a automatizované nasazování instancí. Rozjel jsem a vedl celofiremní shift-left v kvalitě.',
        },
        {
          when: '2016 – 2020',
          where: 'Rohlík.cz · Zonky.cz · Accenture',
          role: 'QA Engineer, Test Engineering Analyst',
          text: 'Automatizace testů pro online supermarket, fintech a enterprise klienty.',
        },
      ],
      certs: 'AI Developer (robot_dreams, 2025) · CS50 (Harvard / edX, 2020)',
    },
    contact: {
      label: 'Kontakt',
      title: 'Ozvěte se',
      text: 'Nabídka práce, projekt nebo otázka k čemukoli výš — napište mi. Adresa je za malým důkazem, že nejste robot sbírající e-maily:',
      hint: 'Dejte mému jménu háček — přetáhněte ˇ na C, nebo na C prostě klepněte.',
      targetLabel: 'Přidat háček na C a zobrazit e-mailovou adresu',
      success: 'Děkuji. Takhle se to píše.',
      copy: 'Kopírovat',
      copied: 'Zkopírováno',
      noscript: 'Bez JavaScriptu: jozef zavináč cambora tečka cz.',
      elsewhere: 'Nebo mě najdete na',
    },
    footer: {
      made: 'Čisté HTML a CSS, žádný framework, hostováno na GitHub Pages.',
      source: 'Zdrojový kód',
      who: 'Jozef Čambora · Praha · 2026',
    },
  },
}
